- name: Build Docker image on control node
  hosts: localhost
  become: true
  tasks:
  
  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    ignore_errors: yes

  - name: Run Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Rebuild Docker image
    command: docker build -t mcm/web-app:latest "{{ playbook_dir }}/Docker"
    args:
      chdir: "{{ playbook_dir }}/Docker"

  - name: Save Docker image as tarball
    command: docker save -o "{{ playbook_dir }}/mcm_webapp.tar" mcm/web-app:latest

  - name: Ensure tarball is readable
    file:
      path: "{{ playbook_dir }}/mcm_webapp.tar"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0644'


- name: Deploy
  hosts: ubuntu, centos
  become: true
  tasks:

  - name: Install Docker (Ubuntu)

  - name: Install Docker (CentOS)

  - name: Run Docker service

  - name: Copy Docker image tarball

  - name: Load Docker image

  - name: Remove existing container

  - name: Run container

  - name: Verify container is running

  - name: Display container status