---
- name: Build Docker images on control node
  hosts: localhost
  become: yes
  vars_files:
    - config.yaml
  roles:
    - control_build

- name: Deploy containers to managed nodes
  hosts: all
  become: yes
  vars_files:
    - config.yaml
  roles:
    - motd
    - deploy_containers
